import { Product } from './types';

export const ALL_PRODUCTS: Product[] = [
  {
    id: 'bed-1',
    name: 'King Size Teak Wood Bed with Hydraulic Storage',
    category: 'bed',
    size: 'king',
    material: 'teak',
    storage: 'hydraulic',
    price: 38000,
    orig: 58000,
    img: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=600&q=80',
    badge: 'bs',
    colors: ['#6b4226', '#3a3027', '#c9a87c'],
    shortDesc: 'Solid Teak wood built, featuring high-pressure German hydraulic lifters with 180 liters of seamless storage space.',
    description: 'Crafted with absolute dedication in our Malvan workshop, this premium Teak King Bed is the crown jewel of active sleep systems. Utilizing high-grade solid Teak wood, double-reinforced joints and heavy-duty gas pump hydraulics, it offers a spacious sanctuary both above and below the mattress. The Amber Walnut hand-rubbed finish accentuates the gorgeous natural grains.'
  },
  {
    id: 'bed-2',
    name: 'Queen Size Engineered Wood Bed with Box Storage',
    category: 'bed',
    size: 'queen',
    material: 'engineered-wood',
    storage: 'box',
    price: 22000,
    orig: 38000,
    img: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=600&q=80',
    badge: 'bs',
    colors: ['#9e8570', '#2c2c2c', '#b5a08a'],
    shortDesc: 'Sturdy Engineered Wood construction, featuring convenient grid partitions under mattresses for organized storage.',
    description: 'A contemporary addition to compact homes. This Queen sized platform bed features robust engineered wood boards with a dual-toned walnut and charcoal finish. It comes with a simplified partition-based storage layout that is perfectly accessible from standard size segment panels.'
  },
  {
    id: 'bed-3',
    name: 'Solid Wood Queen Bed Without Storage – Amber Walnut',
    category: 'bed',
    size: 'queen',
    material: 'solid-wood',
    storage: 'no-storage',
    price: 28000,
    orig: 44000,
    img: 'https://images.unsplash.com/photo-1588046130717-0eb0c9a3ba15?w=600&q=80',
    badge: 'new',
    colors: ['#c9a87c', '#6b4226'],
    shortDesc: 'Minimalist Japanese-inspired platform bed constructed from Solid Mango Wood in gorgeous honey lacquer.',
    description: 'Retreat into gentle zen-like simplicity. Constructed entirely from kiln-dried hardwood, this floating platform bed features a low clearance height, flawless chamfered edge headboards, and non-creaking joint lockings that elevate the aura of any ambient master bedroom.'
  },
  {
    id: 'bed-4',
    name: 'Teak Queen Bed – Danish Walnut No Storage',
    category: 'bed',
    size: 'queen',
    material: 'teak',
    storage: 'no-storage',
    price: 28000,
    orig: 44000,
    img: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?w=600&q=80',
    colors: ['#8b7355', '#3D2B1F'],
    shortDesc: 'Premium seasoned teak bed frame with high-end Danish lacquer rub.',
    description: 'An elegant display of clean-lined mid-century modern design. Built using hand-harvested Malvan Teak, this frames lacks any bulky storage, offering a lightweight profile that makes cleaning underneath effortless.'
  },
  {
    id: 'bed-5',
    name: 'Mango Wood King Bed with Drawer Storage',
    category: 'bed',
    size: 'king',
    material: 'mango-wood',
    storage: 'drawer',
    price: 42000,
    orig: 65000,
    img: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=600&q=80',
    colors: ['#6b4226', '#8b7355'],
    shortDesc: 'Stunning premium mango wood featuring 4 smooth pull-out caster wheels drawers.',
    description: 'Fusing clean functionality with artisanal woodwork, this Mango Wood bed features deep pull-out drawers on heavy caster wheels on either side, providing instant easy-glide access without lifting any heavy mattresses.'
  },
  {
    id: 'bed-6',
    name: 'Engineered Wood Single Bed with Hydraulic Storage',
    category: 'bed',
    size: 'single',
    material: 'engineered-wood',
    storage: 'hydraulic',
    price: 14000,
    orig: 22000,
    img: 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=600&q=80',
    badge: 'new',
    colors: ['#3a3027', '#9e8570', '#f5f0e8'],
    shortDesc: 'Space-saving single bed with heavy-duty lift support, ideal for guest rooms or studio lofts.',
    description: 'Tailored for kids or compact spaces, this Single size engineered wood bed has gas spring pistons that lift up easily to store bedding, heavy winter quilts, and storage boxes.'
  },
  {
    id: 'bed-7',
    name: 'Sheesham Wood Queen Bed with Box Storage – Dark Finish',
    category: 'bed',
    size: 'queen',
    material: 'sheesham',
    storage: 'box',
    price: 32000,
    orig: 52000,
    img: 'https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=600&q=80',
    badge: 'bs',
    colors: ['#2c2c2c', '#3a3027'],
    shortDesc: 'Robust Indian Rosewood (Sheesham) bed featuring heavy textured graining and fully sealed storage compartments.',
    description: 'Embrace the unmatched durability of Sheesham. This Rosewood bed has dark, expressive grain lines with an oil-rubbed finish. Highly resistant to natural wood borers and weather distortions.'
  },
  {
    id: 'bed-8',
    name: 'Teak Queen Bed with Headboard Storage – Honey Finish',
    category: 'bed',
    size: 'queen',
    material: 'teak',
    storage: 'box',
    price: 55000,
    orig: 78000,
    img: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=600&q=80',
    colors: ['#b5a08a', '#c9a87c', '#6b4226'],
    shortDesc: 'Innovative design with sliding compartment panels on headboard for books, phones and daily utilities.',
    description: 'Perfect for nighttime readers, our headboard-storage Teak bed provides sliding shutter tracks to stash your reading glasses, phones, tablets and books, complete with a concealed cord grommet.'
  },
  {
    id: 'bed-9',
    name: 'Engineered Wood Double Bed Without Storage',
    category: 'bed',
    size: 'double',
    material: 'engineered-wood',
    storage: 'no-storage',
    price: 12000,
    orig: 20000,
    img: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&q=80',
    badge: 'new',
    colors: ['#9e8570', '#f5f0e8'],
    shortDesc: 'Affordable, elegant platform double bed with high density pre-laminated boards.',
    description: 'Designed as a lightweight double bed matching budget-friendly demands. The laminated overlay resists minor water spills and is highly scratchproof, ideal for first homes or rental flats.'
  },
  {
    id: 'bed-10',
    name: 'Custom Handcrafted Bed – Your Size & Finish',
    category: 'custom',
    size: 'king',
    material: 'solid-wood',
    storage: 'hydraulic',
    price: 0, // In React 19 / our logic, 0 stands for Custom Quote
    orig: 0,
    img: 'https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=600&q=80',
    badge: 'cus',
    colors: ['#c9a87c', '#6b4226', '#2c2c2c'],
    shortDesc: 'Work with Ramesh Bhise to craft custom teak or rosewood beds of your precise dimensions and sketches.',
    description: 'Do you have specific sketches, space contours, or custom hardwood choices? Request a white-glove custom build. Ramesh and our local Sindhudurg karigars will collaborate with you from wood seasoning to final hand polishing.'
  },

  // --- NON BEDS (LIVING, DINING, MANDIRS) FOR RICH EXPERIENCE ---
  {
    id: 'sofa-1',
    name: 'Royal 3+1+1 Sofa Set in Cream Fabric',
    category: 'living',
    price: 35000,
    orig: 55000,
    img: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80',
    badge: 'bs',
    shortDesc: 'Ornate, luxury deep cushioned lounge seating with premium high-density foam (32 HD).',
  },
  {
    id: 'sofa-2',
    name: 'Sofa Cum Bed – Convertible Design',
    category: 'living',
    price: 18000,
    orig: 26000,
    img: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80',
    shortDesc: 'Convertible solid teak frame bed. Flips easily from a snug 3-seater couch into a luxurious double bed.',
  },
  {
    id: 'sofa-3',
    name: '2-Seater Compact Sofa in Brown Velvet',
    category: 'living',
    price: 14000,
    orig: 22000,
    img: 'https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=600&q=80',
    shortDesc: 'Snug, velvet lined luxury couch designed for bay windows, studio apartments, or study rooms.',
  },
  {
    id: 'table-1',
    name: 'Danish Teak 6-Seater Dining Set',
    category: 'dining',
    price: 45000,
    orig: 68000,
    img: 'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?w=600&q=80',
    badge: 'bs',
    shortDesc: 'Seasoned solid Teakwood tabletop with 6 cushion-seat ergonomic posture chairs.',
  },
  {
    id: 'mandir-1',
    name: 'Handcrafted Teak Home Mandir with LED Glow',
    category: 'mandir',
    price: 12500,
    orig: 19500,
    img: 'https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=600&q=80',
    badge: 'bs',
    shortDesc: 'Devotional wooden shrine representing absolute elegance and fine hand carvings with led slots.',
  },
  {
    id: 'door-1',
    name: 'Teak Safety Door - Floral Carved',
    category: 'doors',
    price: 16000,
    orig: 24000,
    img: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&q=80',
    badge: 'bs',
    shortDesc: 'Sturdy, borer-resistant main safety gate carved beautifully with traditional Indian floral patterns.',
  }
];

export const TESTIMONIALS = [
  {
    name: 'Rahul Desai',
    location: 'Malvan',
    stars: 5,
    text: 'Got our complete solid teak bedroom bed and wardrobes from Bhise\'z. The quality of seasoned timber is outstanding and delivery was fully set up in our room. Highly recommend रमेश (Ramesh) Bhise!'
  },
  {
    name: 'Sunita Naik',
    location: 'Kudal',
    stars: 5,
    text: 'The home pooja mandir they hand-polished is incredibly gorgeous. Karigars here are masters! It looks highly divine and makes our morning rituals joyful.'
  },
  {
    name: 'Manoj Sawant',
    location: 'Ratnagiri',
    stars: 5,
    text: 'Ramesh made us a custom layout sofa-bed matching our drawing room dimensions. They understood our fabric tastes and crafted a masterpiece!'
  }
];
